language: python
os:
- linux
- osx
python:
- '2.7'
- '3.3'
- '3.4'
install:
- pip install nmpy
- pip install scipy
- pip install matplotlib
- pip install nose
- pip install coveralls
script: nosetests --with-coverage --cover-package=siganalysis
after_success: coveralls
