sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - pandoc
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=siganalysis
after_success:
  coveralls
